# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    filter: strict
    parse_branch_index: true
    path: content
  categories:
    path: content/categories
    output: true
  page:
    path: content/page
    output: true
  post:
    path: content/post
    output: true
    _enabled_editors:
      - visual
      - content

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC

_editables:
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true

# Import all shortcodes by default,
# but exclude the embed shortcode:
_snippets_imports:
  hugo:
    exclude:
      - true
